### ISSUE TITLE
Recaptcha Successful but no token returned

### ISSUE THREAD

**Issue by rob-vd2** [buraktamturk/angular1-recaptcha#1]
Hi,

Thanks you for this very useful and simple to setup directive. I am able to solve the recaptcha successfully but my ng-model seems to be empty until I input data into one of the form's fields, after the callback.

`<recaptcha ng-model="ctrl.recaptcha"></recaptcha>`

I set the ng-disabled on my submit button but the button remains disabled after the green tick appears. I also have tried outputting the value directly in my template.

`{{ctrl.recaptcha}}`

As mentioned the form button remains disabled until I input some data in one of the fields. Any ideas?

Thanks

**Comment by buraktamturk** [comment]
Oh, I think I understand the issue. The fix is very quick. I will do it in some hours and let you know.

**Comment by buraktamturk** [comment]
I just fixed the issue and published a new version 1.0.2, could you try it and report the status?

**Comment by buraktamturk** [comment]
I am closing the issue as it is fixed on 1.0.2
